### ISSUE TITLE
Adobe AIR Sdk 23 - iOS Package creation

### ISSUE THREAD

**Issue by mspdevelopers** [distriqt/ANE-Exceptions#1]
In you try to create a ios package (.ipa) using air sdk 23 you will get an error:

ld: in C:\\Users\\[UserName]\\AppData\\Local\\Temp\\070e0752-57aa-4ebd-88a9-8bb434e77cbc/CrashReporter.framework/CrashReporter(libCrashReporter-iphoneos.a-arm64-master.o), unsupported address encoding (19) of personality function in CIE for architecture arm64
Compilation failed while executing : ld64

**Comment by marchbold** [comment]
Hi,

Are you linking against an iOS SDK at all?

**Comment by mspdevelopers** [comment]
Hi, 
 I think that I don't understand the question. 
 I'm just using adt to create a build for iOS.

Am I missing something? Maybe I've been creating my builds in a wrong way.

**Comment by marchbold** [comment]
Not at all, we do suggest you link against an iOS SDK however it's not a requirement for this ANE. 

Anything else you are doing to replicate this error? We aren't having an issue packaging an ipa using AIR 23.

**Comment by mspdevelopers** [comment]
Not really, it works perflectly with air 19.
 Same application.xml, same ANEs, same swcs, same .bat files that creates the .ipa.

Could be related to a mix of ANEs?

> <extensions>
>       <extensionID>com.distriqt.Notifications</extensionID>
>       <extensionID>com.distriqt.InAppBilling</extensionID>
>       <extensionID>com.distriqt.Dialog</extensionID>
>       <extensionID>com.distriqt.Application</extensionID>
>       <extensionID>com.distriqt.Image</extensionID>
>       <extensionID>com.distriqt.AndroidSupport</extensionID>
>       <extensionID>com.distriqt.Core</extensionID>
>       <extensionID>com.distriqt.ApplicationRater</extensionID>
>       <extensionID>com.distriqt.Memory</extensionID>
>       <extensionID>com.distriqt.Exceptions</extensionID>
>   </extensions>

**Comment by marchbold** [comment]
Is there any more to the error?

You should potentially try adding the iOS SDK in, as there have been some major changes since 19 in what AIR includes.

http://airnativeextensions.com/knowledgebase/tutorial/1#ios

**Comment by mspdevelopers** [comment]
Ok, I will try to test this but we don't use OSX to build our game.

**Comment by marchbold** [comment]
You don't need OSX to add the platformsdk option, and you can grab a version of the iOS SDK from that tutorial.

**Comment by mspdevelopers** [comment]
Update:
 I got the iOS sdk from the tutorial.

I added this line to the adt:
-platformsdk C:[Path]\iPhoneOS10.0.sdk

Now I'm getting this:
Warning: The path to platform sdk should end with iPhoneOSx.x or iPhoneSimulatorx.x format to avoid any unintended behavior.
ld: unexpected token: !tapi-tbd-v2 for architecture arm64
ld: unexpected token: !tapi-tbd-v2 for architecture armv7
Compilation failed while executing : ld64

I tried renaming to iPhoneOS10.sdk but it didn't work at all.

**Comment by leefj** [comment]
it seems  AIR 23  is not compatible with  iPhoneOS10.0.sdk,  use 9.x may fine

**Comment by leefj** [comment]
wait for AIR SDK 24

**Comment by mspdevelopers** [comment]
Yep I will wait.
 If I use 9.3 it creates the package properly but only if I don't use the Exceptions ANE in the application.xml
 If I add it it will throw the original exception about the missing CrashReporter lib.

We can close this if you want....

**Comment by marchbold** [comment]
Hi,

Yeah there is a workaround for OSX (macOS) but nothing for windows yet. However there shouldn't be an issue using 9.x for the moment.

I will make a note of the requirement for linking the iOS SDK in the docs.
