### ISSUE TITLE
Can I use this alongside with crashlytics?

### ISSUE THREAD

**Issue by shaymolho** [distriqt/ANE-Exceptions#14]
According to the [docs](https://docs.airnativeextensions.com/docs/exceptions/usage):

> You can generally only have one exception handler in an application. 
So if you are using another library that tracks exceptions (Google Analytics or a bug tracker) then the functionality provided here may not work or may stop the library from working.

But it doesn't mention if this ANE can be used with [Crashlytics](https://firebase.google.com/products/crashlytics),

**Comment by SpikeApp** [comment]
If you need support on how to use Spike or solve a specific issue please join our support group at https://www.facebook.com/groups/spikeapp/

We do NOT give one on one support by e-mail.

Thank you!

The Spike Team

**Comment by marchbold** [comment]
You can try, but I wouldn't suggest it. They may get in the way of each other, and it would probably depend on the order you load them which one catches errors etc.
