### ISSUE TITLE
[Android] How to provoke an exception to see this ANE in action?

### ISSUE THREAD

**Issue by 2jfw** [distriqt/ANE-Exceptions#15]
I was wondering how I could provoke an exception to see this ANE in action, on Android?

One questions regarding this from the "Usage" docs, where it says:

> You can generally only have one exception handler in an application.
> So if you are using another library that tracks exceptions (Google Analytics or a bug tracker) then the functionality provided here may not work or may stop the library from working.

I'm having a global Uncaught Error Handler - would this already interfere with this ANE?

**Comment by marchbold** [comment]
You can use our Debug extension to force a crash.

```as3
Debug.service.forceCrash();
```

- [docs](https://docs.airnativeextensions.com/docs/debug)
- [repo](https://github.com/airnativeextensions/ANE-Debug)

**Comment by 2jfw** [comment]
Thanks, gonna try that out!
