### ISSUE TITLE
is it just as3 uncaughtErrorEvents listener ?

### ISSUE THREAD

**Issue by Xgamefactory** [distriqt/ANE-Exceptions#2]
i have event listener to catch exceptions
uncaughtErrorEvents.addEventListener(UncaughtErrorEvent.UNCAUGHT_ERROR, onUncaughtError);
doest this extension just catching this airs exceptions or it catchs native iso android expcetions caused with this app, too ?

**Comment by marchbold** [comment]
Hi,

This catches native exceptions, not AIR exceptions. So yes is useful when you are having issues with application crashes.

**Comment by Xgamefactory** [comment]
perfect ! so it still catches exceptions event there is eventListener inside flash for uncaughtErrorEvents right ?

**Comment by marchbold** [comment]
Correct it shouldn't affect AS3 Errors.
