### ISSUE TITLE
unsupported address encoding (32) of personality function in CIE for architecture arm64

### ISSUE THREAD

**Issue by quilombodigital** [distriqt/ANE-Exceptions#5]
I am having this error when packaging.

ld: in C:\\Users\\RICARD~1.MEL\\AppData\\Local\\Temp\\5d7ead33-a60a-4779-bb4c-2151b3d9a744/CrashReporter.framework/CrashReporter(libCrashReporter-iphoneos.a-arm64-master.o), unsupported address encoding (32) of personality function in CIE for architecture arm64
Compilation failed while executing : ld64

**Comment by marchbold** [comment]
What version of AIR are you using? Make sure you are using a recent release

**Comment by quilombodigital** [comment]
air version 22, ipad ios9, building in flashbuilder 4.7/windows 10

**Comment by marchbold** [comment]
Could you see if you have the same issue with AIR 24

**Comment by quilombodigital** [comment]
I have tried with version 24 and the same is happening. 
I tried in an empty project and also happened. 
I am currently testing several ANEs from many different companies, and only this one is giving this error.

**Comment by marchbold** [comment]
Are you packaging with an iOS SDK at all?

**Comment by quilombodigital** [comment]
No. I have never needed. I use flashbuilder in Windows, and our projects have dozens of ANEs, with native implementations for IOS and Android, and none of them needed any extra IOS SDK, only AIR SDK.
Are you saying I need to download the xcode+ios_sdk package, extract the ios_sdk, and use it?

**Comment by quilombodigital** [comment]
I have tested by adding the ios sdk 8.4 to the configuration(below), but got the same error.
![tela](https://cloud.githubusercontent.com/assets/874378/23857237/59bef418-07db-11e7-968c-c16eb8139220.png)

**Comment by marchbold** [comment]
Could you try a recent iOS SDK? http://resources.airnativeextensions.com/ios/

**Comment by quilombodigital** [comment]
IOS sdk 9.3, same problem, ios sdk 10.2, another error message:

ld: unexpected token: !tapi-tbd-v2 for architecture arm64
ld: unexpected token: !tapi-tbd-v2 for architecture armv7
Compilation failed while executing : ld64

**Comment by marchbold** [comment]
That issue is a linker issue in AIR 24, AIR 25 has the updated linker for iOS. Could you try AIR 25 and see if the error persists.

**Comment by leefj** [comment]
i use AIR 24 and  iPhoneOS10.2.sdk , it works well

**Comment by marchbold** [comment]
@leefj  You must have updated the linker in your version of the AIR SDK though? 

I believe @quilombodigital is using Windows and I'm not aware of a method for that at the moment, so AIR 25 may be the only solution here.

**Comment by leefj** [comment]
what is "linker" mean ?
i am really use air 24 
<img width="710" alt="2167f9fb-890e-41f5-92a0-e644941f5834" src="https://cloud.githubusercontent.com/assets/12420137/23933944/e90a2eba-097c-11e7-8446-05390c0be0c7.png">

**Comment by quilombodigital** [comment]
Yes, I am building in windows, because it is part of our build pipeline. I tried with airsdk 25, and did not worked. 

Error occurred while packaging the application:
ld: in C:\\Users\\RICARD~1.MEL\\AppData\\Local\\Temp\\ad9cab40-00e3-4d1e-92d4-2308649b070e/CrashReporter.framework/CrashReporter(libCrashReporter-iphoneos.a-arm64-master.o), unsupported encoding in FDE of pointer to function for architecture arm64

**Comment by marchbold** [comment]
Not really sure why you are having that issue. That framework is a well known and supported framework and we haven't had any issues packaging it. 

Could you list the details on how you are packaging your application, perhaps you are doing something outside the normal package process?

**Comment by quilombodigital** [comment]
Well, I just build it in the flashbuilder. I was thinking that this could be a problem related to windows, because I assumed you use mac, but if you are saying a lot of people is using windows, I guess this is a problem in my machine configuration, and this is something strange, since we used other ANEs from distriqt that works.
Thanks anyway. Let me know if this happens again with someone else. :)

**Comment by quilombodigital** [comment]
by the way, I tested at a friend´s machine with windows 7, and the error was exactly the same.

**Comment by marchbold** [comment]
Cheers,

I'll see if there's an update for that framework, but it's not produced by us so it's a little outside our control.

All the source is here if you want to try and build it yourself.
