### ISSUE TITLE
ios crash exceptions not symbolicated

### ISSUE THREAD

**Issue by Xgamefactory** [distriqt/ANE-Exceptions#7]
is it possible to make them fully symbolicated ?
at least partially

see
![tn2151_symbolication_levels](https://user-images.githubusercontent.com/22529051/29486155-c8b7731c-84f0-11e7-815b-114faebaa5d5.png)

https://developer.apple.com/library/content/technotes/tn2151/_index.html

**Comment by marchbold** [comment]
You'll need to locate your `dSYM` file for your application to symbolicate the crash report. You'll find this inside the IPA you generate.

**Comment by Xgamefactory** [comment]
thanks i found a free portable tool for symbolicating ios crash logs on windows machine

https://sourceforge.net/projects/ioscrashlogstool/

**Comment by marchbold** [comment]
Glad you found a solution.
