### ISSUE TITLE
crashreporter.framework Compilation failed while executing : ld64

### ISSUE THREAD

**Issue by Xgamefactory** [distriqt/ANE-Exceptions#9]
```
ld: in C:\\Users\\SAMSUNG\\AppData\\Local\\Temp\\33856d9f-8928-4585-a8cd-c128eb585a9f/CrashReporter.framework/Cr
a-arm64-master.o), sectionForAddress(0x65C17F00021834) address not in any section for architecture arm64
Compilation failed while executing : ld64
```

we are getting this error using latest air sdk.

**Comment by marchbold** [comment]
Are you linking against a version of the iOS SDK?

**Comment by Xgamefactory** [comment]
don't get what you mean ?
this happens when simple building ipa with adt inside latest air sdk 29.

**Comment by marchbold** [comment]
Hi, 

Are you using the platformsdk option in your ADT command? This allows you to link against a version of the iOS SDK.

**Comment by Xgamefactory** [comment]
sorry messed head )
we are not using –platformSDK switch after air 28 sdk.

**Comment by marchbold** [comment]
Yeah okay, it shouldn't be needed then. 

Are you building on Windows? Windows seems to sometimes have issues with iOS frameworks, could you see if you get the error on a macOS machine ?

**Comment by Xgamefactory** [comment]
yes this is win build issue
we have to replace ld64 inside air skd 
with air win sdk original ld64 throwa thiss error.
is this ane ios 64bit compatible ?

**Comment by marchbold** [comment]
Yes this ANE is 64bit compatible.

**Comment by Xgamefactory** [comment]
weird. even with lates air sdk 29.122 we still get this error on windows
so to use this exception we have to build on mac os.

**Comment by marchbold** [comment]
Have you had success on macOS ? There appears to be some issue with the crash reporting framework on windows. We haven't been able to isolate the cause and as the framework is an iOS standard we try not to alter them.

**Comment by Xgamefactory** [comment]
yes it works on mac but win air sdk has tons of problems with ld
the ld64.exe not updated size and timestamp same as with previous versions.

**Comment by aram-ahak** [comment]
Hi guys.
We updated Ane`s, and after that we are getting the same error.
```
AppData\\Local\\Temp\\f34bb674-ac5c-4efc-975d-866317265aaf/FirebaseAuth.framework/FirebaseAuth(FIRAuthAppDelegateProxy.o), sectionForAddress(0x4000001) address not in any section for architecture arm64
Compilation failed while executing : ld64
```
We use:
- Windows AIR SDK version: 30
- iOS SDK version 11.1

**Comment by marchbold** [comment]
@aram-ahak Do you mean that you were packaging successfully before updating the ANEs? What version where you using previously?

**Comment by david-daal** [comment]
Yes, I was packaging successfully before updated the ANEs.
Previously I used 2.0.043 version.

**Comment by aram-ahak** [comment]
Yes, I was packaging successfully before updated the ANEs.
Previously I used 2.0.043 version.

**Comment by marchbold** [comment]
Hi, 2.0.043? That's not a version of the Exceptions ANE? 

Ah, I just noticed the FirebaseAuth reference, please post in the Firebase repository.
